#!/usr/bin/env python
import sys

from utils.helper import *

if __name__ == '__main__':
  init_logging()

  if len(sys.argv) != 2:
    logging.info("argument number should be 2")
    sys.exit(-1)
  partial_process_name = sys.argv[1]
  tmp_process_list = get_process_by_name(partial_process_name)
  terminate_processes_by_inst(tmp_process_list)
